# Generated by Django 5.1 on 2025-07-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=20)),
                ('id_image', models.ImageField(upload_to='tenant_id')),
            ],
            options={
                'verbose_name': 'Tenant Profile',
                'verbose_name_plural': 'Tenant Profiles',
            },
        ),
    ]
