# Generated by Django 5.1 on 2025-07-19 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybill',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.rooms'),
        ),
        migrations.AddField(
            model_name='payment',
            name='monthly_bill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payments.monthlybill'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlybill',
            unique_together={('room', 'month')},
        ),
    ]
