# Generated by Django 5.1 on 2024-08-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[("ROOMS", "Rooms"), ("FLATS", "Flats")],
                        default="ROOMS",
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=20)),
                ("state", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=20)),
                (
                    "zip_code",
                    models.CharField(max_length=12, verbose_name="ZIP / Postal code"),
                ),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
            },
        ),
    ]
