# Generated by Django 5.1 on 2024-08-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0005_rooms_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="rooms",
            name="capacity",
            field=models.IntegerField(default=3),
        ),
    ]
