# Generated by Django 5.1 on 2024-08-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_rooms_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='rent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
