# Generated by Django 5.1 on 2024-08-18 05:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0008_rooms_rent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rooms",
            old_name="rent",
            new_name="base_rent",
        ),
    ]
