# Generated by Django 5.1 on 2025-07-19 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_rename_rent_rooms_base_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.PositiveIntegerField()),
                ('reading_date', models.DateField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=10.0, max_digits=6)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_readings', to='properties.rooms')),
            ],
            options={
                'verbose_name': 'Electricity Reading',
                'verbose_name_plural': 'Electricity Readings',
                'ordering': ['-reading_date'],
                'unique_together': {('room', 'reading_date')},
            },
        ),
    ]
