# Generated by Django 5.1 on 2025-07-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.PositiveIntegerField()),
                ('reading_date', models.DateField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=10.0, max_digits=6)),
            ],
            options={
                'verbose_name': 'Electricity Reading',
                'verbose_name_plural': 'Electricity Readings',
                'ordering': ['-reading_date'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('ROOMS', 'Rooms'), ('FLATS', 'Flats')], default='ROOMS', max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP / Postal code')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=20)),
                ('capacity', models.IntegerField(default=3)),
                ('base_rent', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
    ]
